#!/usr/bin/env python3
"""
Generate .def file for DLL proxy from original DLL exports

Usage:
    python generate_exports.py original.dll > exports.def
"""

import sys
import subprocess
import re

def get_dll_exports(dll_path):
    """Extract export names from DLL using dumpbin or objdump"""

    # Try dumpbin first (MSVC tool)
    try:
        result = subprocess.run(
            ['dumpbin', '/EXPORTS', dll_path],
            capture_output=True,
            text=True,
            check=True
        )
        return parse_dumpbin_output(result.stdout)
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass

    # Try objdump (MinGW tool)
    try:
        result = subprocess.run(
            ['objdump', '-p', dll_path],
            capture_output=True,
            text=True,
            check=True
        )
        return parse_objdump_output(result.stdout)
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass

    # Try pefile (Python library)
    try:
        import pefile
        return parse_with_pefile(dll_path)
    except ImportError:
        pass

    print("ERROR: No suitable tool found!", file=sys.stderr)
    print("Install one of:", file=sys.stderr)
    print("  - Visual Studio (for dumpbin)", file=sys.stderr)
    print("  - MinGW (for objdump)", file=sys.stderr)
    print("  - pip install pefile", file=sys.stderr)
    sys.exit(1)

def parse_dumpbin_output(output):
    """Parse dumpbin /EXPORTS output"""
    exports = []
    in_exports = False

    for line in output.splitlines():
        if 'ordinal' in line.lower() and 'name' in line.lower():
            in_exports = True
            continue

        if in_exports:
            # Format: ordinal hint RVA      name
            parts = line.split()
            if len(parts) >= 4:
                name = parts[3]
                # Skip if it's a number (ordinal only export)
                if not name.isdigit():
                    exports.append(name)

    return exports

def parse_objdump_output(output):
    """Parse objdump -p output"""
    exports = []
    in_exports = False

    for line in output.splitlines():
        if '[Ordinal/Name Pointer] Table' in line:
            in_exports = True
            continue

        if in_exports:
            # Format varies, but typically: [ordinal] name
            match = re.search(r'\[\s*\d+\]\s+(\S+)', line)
            if match:
                exports.append(match.group(1))
            elif line.strip() == '':
                in_exports = False

    return exports

def parse_with_pefile(dll_path):
    """Parse using pefile library"""
    import pefile

    pe = pefile.PE(dll_path)
    exports = []

    if hasattr(pe, 'DIRECTORY_ENTRY_EXPORT'):
        for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
            if exp.name:
                exports.append(exp.name.decode('utf-8'))

    return exports

def generate_def_file(dll_path, exports):
    """Generate .def file content"""

    print(f"; Export definitions for {dll_path}")
    print(f"; Generated by generate_exports.py")
    print(f"; Total exports: {len(exports)}")
    print()
    print("LIBRARY")
    print("EXPORTS")

    for export in exports:
        # For .NET DLLs, we handle these manually in the C code
        if export in ['_CorDllMain', '_CorExeMain', '_CorImageUnloading', '_CorValidateImage']:
            print(f"    ; {export} - handled in C code")
        else:
            print(f"    {export} = orig.{export}")

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <dll_path>", file=sys.stderr)
        print(f"Example: {sys.argv[0]} System.Windows.Forms.dll > exports.def", file=sys.stderr)
        sys.exit(1)

    dll_path = sys.argv[1]

    print(f"[*] Analyzing {dll_path}...", file=sys.stderr)
    exports = get_dll_exports(dll_path)

    if not exports:
        print(f"ERROR: No exports found in {dll_path}", file=sys.stderr)
        sys.exit(1)

    print(f"[*] Found {len(exports)} exports", file=sys.stderr)
    print(f"[*] Generating .def file...", file=sys.stderr)

    generate_def_file(dll_path, exports)

    print(f"[*] Done! Redirect output to a .def file", file=sys.stderr)

if __name__ == '__main__':
    main()
