param(
    [string]$AssemblyPath = (Join-Path $PSScriptRoot "..\orig.dll"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\TypeForwarders.cs")
)

$ErrorActionPreference = "Stop"

$ildasmCandidates = @(
    "${env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\x64\ildasm.exe",
    "${env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\ildasm.exe",
    "${env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\ildasm.exe",
    "${env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\ildasm.exe"
)

$ildasm = $ildasmCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $ildasm) {
    throw "ildasm.exe not found. Install .NET Framework SDK tools or update the path in this script."
}

if (-not (Test-Path $AssemblyPath)) {
    throw "Assembly not found: $AssemblyPath"
}

function Convert-ToCSharpTypeName([string]$metadataName) {
    [regex]::Replace($metadataName, '`\d+', {
        param($match)
        $arity = [int]$match.Value.Substring(1)
        if ($arity -le 1) {
            return "<>"
        }
        return "<" + ("," * ($arity - 1)) + ">"
    })
}

$typeNames = New-Object System.Collections.Generic.List[string]
$lines = & $ildasm /TEXT /PUBONLY /UTF8 $AssemblyPath 2>$null

foreach ($line in $lines) {
    if ($line -notmatch '^\s*\.class\s+') {
        continue
    }
    if ($line -match '\bnested\b') {
        continue
    }
    if ($line -notmatch '\bpublic\b') {
        continue
    }
    if ($line -match '(?<name>dnlib(?:\.[A-Za-z_][A-Za-z0-9_]*(?:`\d+)?)+)(?:<|\s|$)') {
        $typeNames.Add($matches["name"]) | Out-Null
    }
}

$uniqueTypeNames = $typeNames | Sort-Object -Unique
if ($uniqueTypeNames.Count -eq 0) {
    throw "No public dnlib types were found in $AssemblyPath"
}

$output = New-Object System.Collections.Generic.List[string]
$output.Add("extern alias real;") | Out-Null
$output.Add("") | Out-Null
$output.Add("// Generated by tools/GenerateTypeForwarders.ps1 from orig.dll.") | Out-Null
$output.Add("// Re-run the script after replacing orig.dll with a different dnlib build.") | Out-Null
$output.Add("") | Out-Null

foreach ($metadataName in $uniqueTypeNames) {
    $csName = Convert-ToCSharpTypeName $metadataName
    $output.Add("[assembly: global::System.Runtime.CompilerServices.TypeForwardedTo(typeof(real.$csName))]") | Out-Null
}

Set-Content -Path $OutputPath -Value $output -Encoding UTF8
Write-Host "Generated $($uniqueTypeNames.Count) type forwarders -> $OutputPath"
